name: Pytest

on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest]
        exclude:
          # TODO: install snappy compression lib for windows
          - os: windows-latest
            python-version: '3.11'
    name: ${{ matrix.os }}-${{ matrix.python-version }}-pytest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        name: Install Snappy
        run: |
          sudo apt install libsnappy-dev

      - name: Pip install
        shell: bash -l {0}
        run: |
          pip install --upgrade pip setuptools
          pip install .[test]

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v
